/**
 * MariaDB schema — Nexora QR
 *
 * IDs are generated by the application and stored as UUID strings. Keeping
 * engine-specific defaults out of the schema makes a later PostgreSQL move a
 * data migration rather than a product-model rewrite.
 */
import { relations } from "drizzle-orm";
import {
  bigint,
  boolean,
  date,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

import type { QrPayload, QrStyle } from "@/qr/types";

const uuid = (name: string) => varchar(name, { length: 36 });
const utcTimestamp = (name: string) => timestamp(name, { fsp: 3, mode: "date" });

/** Better Auth core tables. Export names intentionally match its model names. */
export const user = mysqlTable("user", {
  id: uuid("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: utcTimestamp("created_at").notNull().defaultNow(),
  updatedAt: utcTimestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const session = mysqlTable(
  "session",
  {
    id: uuid("id").primaryKey(),
    expiresAt: utcTimestamp("expires_at").notNull(),
    token: varchar("token", { length: 255 }).notNull(),
    createdAt: utcTimestamp("created_at").notNull().defaultNow(),
    updatedAt: utcTimestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    uniqueIndex("session_token_uidx").on(table.token),
    index("session_user_idx").on(table.userId),
  ],
);

export const account = mysqlTable(
  "account",
  {
    id: uuid("id").primaryKey(),
    issuer: varchar("issuer", { length: 191 }).notNull(),
    accountId: varchar("account_id", { length: 191 }).notNull(),
    providerId: text("provider_id").notNull(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: utcTimestamp("access_token_expires_at"),
    refreshTokenExpiresAt: utcTimestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: utcTimestamp("created_at").notNull().defaultNow(),
    updatedAt: utcTimestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex("account_issuer_account_uidx").on(table.issuer, table.accountId),
    index("account_user_idx").on(table.userId),
  ],
);

/**
 * Better Auth resolves an authenticated session with a relational
 * `session -> user` query. Foreign keys alone are not enough for Drizzle's
 * relational query builder, so keep these exported relation descriptors next
 * to the core auth tables.
 */
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

export const verification = mysqlTable(
  "verification",
  {
    id: uuid("id").primaryKey(),
    identifier: varchar("identifier", { length: 255 }).notNull(),
    value: text("value").notNull(),
    expiresAt: utcTimestamp("expires_at").notNull(),
    createdAt: utcTimestamp("created_at").notNull().defaultNow(),
    updatedAt: utcTimestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const subscriptions = mysqlTable("subscriptions", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  plan: mysqlEnum("plan", ["free", "pro", "business"]).notNull().default("free"),
  status: mysqlEnum("status", [
    "active",
    "trialing",
    "past_due",
    "canceled",
    "incomplete",
  ])
    .notNull()
    .default("active"),
  provider: varchar("provider", { length: 64 }),
  providerCustomerId: varchar("provider_customer_id", { length: 191 }),
  providerSubscriptionId: varchar("provider_subscription_id", { length: 191 }),
  currentPeriodEnd: utcTimestamp("current_period_end"),
  updatedAt: utcTimestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const folders = mysqlTable(
  "folders",
  {
    id: uuid("id").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 160 }).notNull(),
    createdAt: utcTimestamp("created_at").notNull().defaultNow(),
  },
  (table) => [index("folders_user_idx").on(table.userId)],
);

export const qrCodes = mysqlTable(
  "qr_codes",
  {
    id: uuid("id").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    folderId: uuid("folder_id").references(() => folders.id, { onDelete: "set null" }),
    name: varchar("name", { length: 160 }).notNull(),
    mode: mysqlEnum("mode", ["static", "dynamic"]).notNull().default("static"),
    contentType: mysqlEnum("content_type", [
      "url",
      "text",
      "wifi",
      "vcard",
      "email",
      "sms",
      "tel",
      "geo",
      "event",
      "promptpay",
    ]).notNull(),
    payload: json("payload").$type<QrPayload>().notNull(),
    style: json("style").$type<QrStyle>().notNull(),
    shortCode: varchar("short_code", { length: 32 }),
    targetUrl: text("target_url"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: utcTimestamp("created_at").notNull().defaultNow(),
    updatedAt: utcTimestamp("updated_at")
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("qr_codes_user_created_idx").on(table.userId, table.createdAt),
    index("qr_codes_folder_idx").on(table.folderId),
    uniqueIndex("qr_codes_short_code_uidx").on(table.shortCode),
  ],
);

export const qrTargetHistory = mysqlTable(
  "qr_target_history",
  {
    id: bigint("id", { mode: "number", unsigned: true }).autoincrement().primaryKey(),
    qrCodeId: uuid("qr_code_id")
      .notNull()
      .references(() => qrCodes.id, { onDelete: "cascade" }),
    oldUrl: text("old_url"),
    newUrl: text("new_url").notNull(),
    changedBy: uuid("changed_by").references(() => user.id, { onDelete: "set null" }),
    changedAt: utcTimestamp("changed_at").notNull().defaultNow(),
  },
  (table) => [index("qr_target_history_qr_idx").on(table.qrCodeId, table.changedAt)],
);

/** Raw events never contain a raw IP address. Free-plan retention is 30 days. */
export const scans = mysqlTable(
  "scans",
  {
    id: bigint("id", { mode: "number", unsigned: true }).autoincrement().primaryKey(),
    qrCodeId: uuid("qr_code_id")
      .notNull()
      .references(() => qrCodes.id, { onDelete: "cascade" }),
    scannedAt: utcTimestamp("scanned_at").notNull().defaultNow(),
    ipHash: varchar("ip_hash", { length: 128 }),
    country: varchar("country", { length: 2 }),
    city: varchar("city", { length: 160 }),
    deviceType: mysqlEnum("device_type", [
      "mobile",
      "tablet",
      "desktop",
      "bot",
      "unknown",
    ])
      .notNull()
      .default("unknown"),
    os: varchar("os", { length: 120 }),
    browser: varchar("browser", { length: 120 }),
    referrer: text("referrer"),
  },
  (table) => [index("scans_qr_time_idx").on(table.qrCodeId, table.scannedAt)],
);

export const scanDaily = mysqlTable(
  "scan_daily",
  {
    qrCodeId: uuid("qr_code_id")
      .notNull()
      .references(() => qrCodes.id, { onDelete: "cascade" }),
    day: date("day", { mode: "string" }).notNull(),
    country: varchar("country", { length: 2 }).notNull().default(""),
    deviceType: mysqlEnum("device_type", [
      "mobile",
      "tablet",
      "desktop",
      "bot",
      "unknown",
    ])
      .notNull()
      .default("unknown"),
    count: int("count", { unsigned: true }).notNull().default(0),
  },
  (table) => [
    uniqueIndex("scan_daily_uidx").on(
      table.qrCodeId,
      table.day,
      table.country,
      table.deviceType,
    ),
    index("scan_daily_qr_day_idx").on(table.qrCodeId, table.day),
  ],
);

/** Historical alias for Phase 1 code and reports. */
export const users = user;
